### ISSUE TITLE
Add automatic removal of permanently bounced emails via webhook

### ISSUE THREAD

**Issue by nekromoff** [nekromoff/eia-scraper#14]
https://documentation.mailgun.com/en/latest/user_manual.html#webhooks

1. On event type: permanent failure
2. Send webhook notification to URL endpoint that will remove that email from `watchers` (any existing record with that email).

Use signed webhook to verify Mailgun: https://documentation.mailgun.com/en/latest/user_manual.html#webhooks

**Comment by martinmacko47** [comment]
Nasadene, este cakame kym Dano prida do Mailgun Webhook na adresu:
https://eia.cyklokoalicia.sk/api/permanent-failure

**Comment by nekromoff** [comment]
zabudol som, pridane
