### ISSUE TITLE
 Symfony\Component\DomCrawler\Crawler::extract(): Argument #1 ($attributes) must be of type array, string given, called in /var/www/sub/eia/app/Http/Controllers/EIAController.php on line 196

### ISSUE THREAD

**Issue by nekromoff** [nekromoff/eia-scraper#50]
Zacala vyskakovat tato chyba, viete to pls fixnut? Este predtym si premazte fingerprint v systemstate, lebo inak nezbehne crawl a chybu neuvidite.

![image](https://user-images.githubusercontent.com/8550349/172139964-e4882095-d563-4df0-88ee-28111de02dd6.png)

**Comment by martinmacko47** [comment]
Fixnute
